services:
  #front
  front: 
    build: 
      context: ..
      dockerfile: ./dockerfiles/Dockerfile.front
    ports: 
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes: 
      - ../:/app
      - /app/node_modules
    networks:
      - nodejs-mysql-network

  #back
  back: 
    build: 
      context: ../app/server
      dockerfile: ../../dockerfiles/Dockerfile.back
    ports: 
      - 3000:3000
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=mysqldb
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../app/server:/app/server
      - /app/server/node_modules
    networks:
      - nodejs-mysql-network

  #db
  mysqldb: 
    image: mysql:8.0.33
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

volumes:
  mysql-data:

networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network
    external: true

